
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.hluther.parser;

/** CUP generated class containing symbol constants. */
public class GameSaveFileSym {
  /* terminals */
  public static final int MAP = 10;
  public static final int SQUAREBRACKETO = 6;
  public static final int ARRIVALTURN = 24;
  public static final int ORANGE = 45;
  public static final int TARGETROW = 55;
  public static final int SHOWSTATISTICS = 16;
  public static final int WHITE = 49;
  public static final int CYAN = 47;
  public static final int DEATHRATE = 30;
  public static final int SQUAREBRACKETC = 7;
  public static final int SHOWSPACESHIPS = 15;
  public static final int DOUBLE = 53;
  public static final int INTEGER = 22;
  public static final int SENDINGS = 26;
  public static final int INITIALROW = 25;
  public static final int HUMAN = 34;
  public static final int INITIALCOLUMN = 54;
  public static final int ROWS = 18;
  public static final int RED = 44;
  public static final int TYPE = 33;
  public static final int COLUMN = 21;
  public static final int COMMA = 9;
  public static final int CURLYBRACKETO = 4;
  public static final int PLANETS = 28;
  public static final int NEUTRALTYPE = 39;
  public static final int MAGENTA = 50;
  public static final int EOF = 0;
  public static final int CURLYBRACKETC = 5;
  public static final int BLIND = 12;
  public static final int ACCUMULATE = 13;
  public static final int TRUE = 51;
  public static final int SIZE = 11;
  public static final int NEUTRAL = 14;
  public static final int error = 1;
  public static final int COMPLETION = 27;
  public static final int HARD = 36;
  public static final int PLAYERS = 32;
  public static final int NAMEPLAYER = 3;
  public static final int SPACESHIPS = 29;
  public static final int NAME = 37;
  public static final int COLOR = 40;
  public static final int OWNER = 38;
  public static final int COLON = 8;
  public static final int INITIALTURN = 23;
  public static final int YELLOW = 42;
  public static final int EASY = 35;
  public static final int COLUMNS = 19;
  public static final int NEUTRALPLANETS = 31;
  public static final int DARKGRAY = 48;
  public static final int ROW = 20;
  public static final int BLUE = 41;
  public static final int NAMEPLANET = 2;
  public static final int PRODUCTION = 17;
  public static final int TARGETCOLUMN = 56;
  public static final int GREEN = 43;
  public static final int FALSE = 52;
  public static final int LIGHTGRAY = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NAMEPLANET",
  "NAMEPLAYER",
  "CURLYBRACKETO",
  "CURLYBRACKETC",
  "SQUAREBRACKETO",
  "SQUAREBRACKETC",
  "COLON",
  "COMMA",
  "MAP",
  "SIZE",
  "BLIND",
  "ACCUMULATE",
  "NEUTRAL",
  "SHOWSPACESHIPS",
  "SHOWSTATISTICS",
  "PRODUCTION",
  "ROWS",
  "COLUMNS",
  "ROW",
  "COLUMN",
  "INTEGER",
  "INITIALTURN",
  "ARRIVALTURN",
  "INITIALROW",
  "SENDINGS",
  "COMPLETION",
  "PLANETS",
  "SPACESHIPS",
  "DEATHRATE",
  "NEUTRALPLANETS",
  "PLAYERS",
  "TYPE",
  "HUMAN",
  "EASY",
  "HARD",
  "NAME",
  "OWNER",
  "NEUTRALTYPE",
  "COLOR",
  "BLUE",
  "YELLOW",
  "GREEN",
  "RED",
  "ORANGE",
  "LIGHTGRAY",
  "CYAN",
  "DARKGRAY",
  "WHITE",
  "MAGENTA",
  "TRUE",
  "FALSE",
  "DOUBLE",
  "INITIALCOLUMN",
  "TARGETROW",
  "TARGETCOLUMN"
  };
}

