
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.hluther.parser;

/** CUP generated class containing symbol constants. */
public class MapConfigFileSym {
  /* terminals */
  public static final int MAP = 11;
  public static final int SQUAREBRACKETO = 7;
  public static final int PLAYERPLANETS = 31;
  public static final int RANDOM = 16;
  public static final int SHOWSTATISTICS = 23;
  public static final int DEATHRATE = 28;
  public static final int SQUAREBRACKETC = 8;
  public static final int SHOWSPACESHIPS = 22;
  public static final int DOUBLE = 39;
  public static final int INTEGER = 20;
  public static final int HUMAN = 33;
  public static final int ROWS = 14;
  public static final int TYPE = 32;
  public static final int COMMA = 10;
  public static final int CURLYBRACKETO = 5;
  public static final int PLANETS = 26;
  public static final int ID = 12;
  public static final int EOF = 0;
  public static final int CURLYBRACKETC = 6;
  public static final int BLIND = 18;
  public static final int ACCUMULATE = 19;
  public static final int TRUE = 37;
  public static final int SIZE = 13;
  public static final int NEUTRAL = 21;
  public static final int error = 1;
  public static final int COMPLETION = 25;
  public static final int HARD = 35;
  public static final int NAMEID = 2;
  public static final int PLAYERS = 30;
  public static final int NAMEPLAYER = 4;
  public static final int SPACESHIPS = 27;
  public static final int NEUTRALP = 17;
  public static final int NAME = 36;
  public static final int COLON = 9;
  public static final int COLUMNS = 15;
  public static final int EASY = 34;
  public static final int NEUTRALPLANETS = 29;
  public static final int NAMEPLANET = 3;
  public static final int PRODUCTION = 24;
  public static final int FALSE = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NAMEID",
  "NAMEPLANET",
  "NAMEPLAYER",
  "CURLYBRACKETO",
  "CURLYBRACKETC",
  "SQUAREBRACKETO",
  "SQUAREBRACKETC",
  "COLON",
  "COMMA",
  "MAP",
  "ID",
  "SIZE",
  "ROWS",
  "COLUMNS",
  "RANDOM",
  "NEUTRALP",
  "BLIND",
  "ACCUMULATE",
  "INTEGER",
  "NEUTRAL",
  "SHOWSPACESHIPS",
  "SHOWSTATISTICS",
  "PRODUCTION",
  "COMPLETION",
  "PLANETS",
  "SPACESHIPS",
  "DEATHRATE",
  "NEUTRALPLANETS",
  "PLAYERS",
  "PLAYERPLANETS",
  "TYPE",
  "HUMAN",
  "EASY",
  "HARD",
  "NAME",
  "TRUE",
  "FALSE",
  "DOUBLE"
  };
}

